### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by himura-kenshin** [Meituan-Dianping/MyFlash#3]
[root@testdb ~]# flashback --binlogFileNames=3999-binlog.000005 --sqlTypes=delete --databaseNames=testdb --tableNames=a --outBinlogFileNameBase=aaa  --logLevel=debug
** (flashback:6719): DEBUG: just skip the FORMAT_DESCRIPTION_EVENT 

** (flashback:6719): DEBUG: have 1167371 events 
Killed

select version();
+---------------+
| version()     |
+---------------+
| 5.7.19-17-log |
+---------------+
1 row in set (0.00 sec)

**Comment by mark-neil-wang** [comment]
看样子是你内存不够啊
